[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = false
skip-lint = true

[programs.localnet]
level_4 = "D51vhx6jAbBtQVwo1fcYr7RMKQKAAnSUy6v7vRCHCZL3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/exploit.ts"


[[test.validator.account]]
address = "Gi2wpf29MLsgMZWmUEtVndB2BKX5TLyEhdWt4bBWGVrP"
filename = "accounts/escrow.json"

[[test.validator.account]]
address = "2Me5B53SU2z5eC5ig8oyMuWosryVyMjsXRnvxx5cVwqv"
filename = "accounts/escrowTokenAccount.json"


[[test.validator.account]]
address = "RzJdKwZLe2hB8KgsE87YwXJQKTHFnAGiV4hAuC94nGa"
filename = "accounts/hackerTokenAccount.json"

[[test.validator.account]]
address = "DLnC1zbKwRX9BjcM9ZuV8uvXaqFY5JhhGWAuY7gVtwXD"
filename = "accounts/usdc.json"


[[test.validator.account]]
address = "J6oF4UUqWEW7YW3c4CNHWZybe2oMYSpHni8Su445fkt5"
filename = "accounts/sender.json"


[[test.validator.account]]
address = "2CoFvgSNNV7oZcujdPV7Pe79GUdBuLkTKZvuKDZASrp8"
filename = "accounts/senderTokenAccount.json"
