[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = false
skip-lint = false

[programs.localnet]
account_reloading = "FkeyV5F9SVuq6hbMqtxrHqX1MDHrwQ2jsNug1MaBN9jf"
update-account = "7xFkBW5msPRF1cHcm5LESpUMfsZALh2heLUEDuPPY6RP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
